

drop table if exists sfdc.onb2__invoice__c;

  
create table sfdc.onb2__invoice__c ( 
CreatedById CHAR(400) , 
CreatedDate TIMESTAMP , 
CurrencyIsoCode  VARCHAR(1000)  , 
ESRExportDate__c  DATE  , 
Id  CHAR(400) ,
IsDeleted  BOOLEAN  ,
LastActivityDate    DATE  ,
LastModifiedById  CHAR(400) ,
LastModifiedDate  TIMESTAMP ,
Name  VARCHAR(8000) ,
ONB2__AccountName__c    VARCHAR(8000) ,
ONB2__Account__c  CHAR(400) ,
ONB2__BalanceDifference__c    NUMERIC ,
ONB2__Balance__c  NUMERIC ,
ONB2__BankAccountOwner__c VARCHAR(8000) ,
ONB2__BankAccount__c  VARCHAR(8000) ,
ONB2__BankCode__c  VARCHAR(8000)  ,
ONB2__BillingAddress__c TEXT  ,
ONB2__BillingCity__c  VARCHAR(8000) ,
ONB2__BillingCountry__c VARCHAR(8000) ,
ONB2__BillingPostalCode__c    VARCHAR(8000) ,
ONB2__BillingState__c VARCHAR(8000) ,
ONB2__BillingStreet__c  VARCHAR(8000) ,
ONB2__CancelationReason__c    VARCHAR(1000) ,
ONB2__CanceledWith__c CHAR(400) ,
ONB2__Class__c  VARCHAR(8000) ,
ONB2__Contact__c  CHAR(400) ,
ONB2__ConversionRate__c NUMERIC ,
ONB2__Date__c DATE  ,
ONB2__DaysOverdue__c   NUMERIC  ,
ONB2__DirectDebitMandateGranted__c   DATE ,
ONB2__DirectDebitMandateReference__c  VARCHAR(8000) ,
ONB2__DirectDebitSequenceType__c  VARCHAR(1000) ,
ONB2__DiscountAmount__c NUMERIC ,
ONB2__DiscountMessage__c  TEXT  ,
ONB2__DiscountPaymentDueDate__c  DATE ,
ONB2__DiscountPaymentDue__c NUMERIC ,
ONB2__DiscountRate__c NUMERIC ,
ONB2__DiscountedNextPaymentDue__c NUMERIC,
ONB2__DiscountedTotalGross__c NUMERIC ,
ONB2__DisplayTransactionTables__c BOOLEAN ,
ONB2__DisplayType__c  VARCHAR(8000) ,
ONB2__DunningLevel__c NUMERIC ,
ONB2__EmailBCC__c TEXT  ,
ONB2__EmailContact__c CHAR(400) ,
ONB2__EmailError__c TEXT  ,
ONB2__EmailFirstName__c  VARCHAR(8000)  ,
ONB2__EmailInvoiceCc__c TEXT  ,
ONB2__EmailInvoice__c BOOLEAN ,
ONB2__EmailLastName__c  VARCHAR(8000) ,
ONB2__EmailSalutation__c  VARCHAR(8000) ,
ONB2__EmailStatus__c  VARCHAR(1000) ,
ONB2__Email__c  VARCHAR(400)  ,
ONB2__Exported__c VARCHAR(8000) ,
ONB2__Footer__c TEXT  ,
ONB2__GrandTotal__c  NUMERIC  ,
ONB2__GrossInvoice__c BOOLEAN ,
ONB2__Header__c TEXT  ,
ONB2__InfoLeft__c TEXT  ,
ONB2__InfoRight__c  TEXT  ,
ONB2__Installment__c  NUMERIC ,
ONB2__InvoiceRun__c CHAR(400) ,
ONB2__LastDunningDate__c    DATE  ,
ONB2__MailingCity__c  VARCHAR(8000) ,
ONB2__MailingCountry__c VARCHAR(8000) ,
ONB2__MailingFirstName__c VARCHAR(8000) ,
ONB2__MailingLastName__c  VARCHAR(8000) ,
ONB2__MailingPostalCode__c  VARCHAR(8000) ,
ONB2__MailingSalutation__c VARCHAR(8000)  ,
ONB2__MailingState__c VARCHAR(8000) ,
ONB2__MailingStreet__c  VARCHAR(8000) ,
ONB2__NextPaymentDueDate__c  DATE ,
ONB2__NextPaymentDue__c NUMERIC ,
ONB2__OutstandingInvoicesText__c   TEXT ,
ONB2__PDF__c  VARCHAR(2000) ,
ONB2__PageHeader__c TEXT  ,
ONB2__PaymentCyclePeriod__c VARCHAR(1000) ,
ONB2__PaymentCycles__c  NUMERIC ,
ONB2__PaymentDate__c  DATE  ,
ONB2__PaymentDueDate__c  DATE ,
ONB2__PaymentDue__c NUMERIC ,
ONB2__PaymentInfo__c  TEXT  ,
ONB2__PaymentMethod__c  VARCHAR(1000) ,
ONB2__PrintContact__c CHAR(400) ,
ONB2__PrintInvoice__c BOOLEAN ,
ONB2__RecipientAddress__c TEXT  ,
ONB2__RelatedInvoice__c CHAR(400) ,
ONB2__Review__c VARCHAR(1000) ,
ONB2__SenderAddress__c   VARCHAR(8000)  ,
ONB2__SepaPaymentError__c VARCHAR(8000) ,
ONB2__ServicePeriodEnd__c DATE  ,
ONB2__ServicePeriodStart__c DATE  ,
ONB2__ShippingCity__c VARCHAR(8000) ,
ONB2__ShippingCountry__c  VARCHAR(8000) ,
ONB2__ShippingPostalCode__c VARCHAR(8000) ,
ONB2__ShippingState__c  VARCHAR(8000) ,
ONB2__ShippingStreet__c VARCHAR(8000) ,
ONB2__Status__c VARCHAR(1000) ,
ONB2__Subscription__c CHAR(400) ,
ONB2__Template__c CHAR(400) ,
ONB2__Tenant__c VARCHAR(8000) ,
ONB2__Text1__c  TEXT  ,
ONB2__Text2__c  TEXT  ,
ONB2__Text3__c TEXT ,
ONB2__TotalNet__c NUMERIC ,
ONB2__TotalTax__c NUMERIC ,
ONB2__Type__c VARCHAR(1000) ,
ONB2__UUID__c VARCHAR(8000) ,
OwnerId CHAR(400) ,
SystemModstamp   TIMESTAMP  ,
bESRExportDone__c BOOLEAN ,
object_type  VARCHAR(200)  );

ALTER TABLE ONLY sfdc.onb2__invoice__c
    ADD CONSTRAINT onb2__invoice__c_pkey PRIMARY KEY (Id,LastModifiedDate);



drop table if exists sfdc.onb2__item__c;

create table sfdc.onb2__item__c (
CreatedById CHAR(400),
CreatedDate TIMESTAMP,
CurrencyIsoCode VARCHAR(1000),
Id  CHAR(400),
IsDeleted BOOLEAN,
LastModifiedById  CHAR(400),
LastModifiedDate  TIMESTAMP,
Name  VARCHAR(8000),
ONB2__Active__c BOOLEAN,
ONB2__AdditionalDescription__c  TEXT,
ONB2__AdditionalTitle__c  TEXT,
ONB2__AggregateIndividualPriced__c  BOOLEAN,
ONB2__BillingPeriod__c  NUMERIC,
ONB2__BillingType__c  VARCHAR(1000),
ONB2__BillingUnit__c  VARCHAR(1000),
ONB2__ChargeModel__c  VARCHAR(1000),
ONB2__Commission__c NUMERIC,
ONB2__ContractValueCorrection__c  NUMERIC,
ONB2__ContractValueInvoiced__c  NUMERIC,
ONB2__ContractValueRemaining__c NUMERIC,
ONB2__ContractValue__c  NUMERIC,
ONB2__DecimalPlacesForQuantity__c NUMERIC,
ONB2__DecimalPlacesForUnitPrice__c  NUMERIC,
ONB2__Description__c  TEXT,
ONB2__Discount__c NUMERIC,
ONB2__DisplaySubtotalAfter__c BOOLEAN,
ONB2__EndDate__c  DATE,
ONB2__GlobalMonthlyMinimum__c BOOLEAN,
ONB2__IgnoreCriterion__c  BOOLEAN,
ONB2__InvoiceLineItemType__c  VARCHAR(1000),
ONB2__NextInvoice__c  DATE,
ONB2__PriceType__c  VARCHAR(1000),
ONB2__Price__c  NUMERIC,
ONB2__ProductGroup__c VARCHAR(8000),
ONB2__Quantity__c NUMERIC,
ONB2__Sequence__c NUMERIC,
ONB2__StartDate__c  DATE,
ONB2__Subscription__c CHAR(400),
ONB2__SyncWith__c VARCHAR(1000),
ONB2__Title__c  TEXT,
ONB2__TransactionPriceField__c  VARCHAR(8000),
ONB2__TransactionPriceTierQuantityField__c  VARCHAR(8000),
ONB2__TransactionQuantityField__c VARCHAR(8000),
ONB2__TransactionType__c  VARCHAR(1000),
ONB2__Unit__c VARCHAR(1000),
OwnerId CHAR(400),
SalesMRR__c NUMERIC,
SystemModstamp  TIMESTAMP,
bIsBundle__c  BOOLEAN,
bIsHardware__c  BOOLEAN,
bIsModule__c  BOOLEAN,
bIsRecurring__c BOOLEAN,
bIsTrialItem__c BOOLEAN,
bRenewItem__c BOOLEAN,
fmlActiveMRR__c NUMERIC,
fmlChannel__c VARCHAR(8000),
fmlDiscountedMRR__c NUMERIC,
fmlItemPriceDiscounted__c NUMERIC,
fmlNextInvoiceValue__c  NUMERIC,
fmlNextRevenue__c NUMERIC,
fmlTerm__c  NUMERIC,
plChannelCountryCode__c VARCHAR(1000),
plChannelSalesType__c VARCHAR(1000),
plChannelUserRole__c  VARCHAR(1000),
plFinancialReporting_ProductClass__c  VARCHAR(1000),
refContract__c  CHAR(400),
refOpportunity__c CHAR(400),
refParentItem__c  CHAR(400),
refProduct2__c  CHAR(400),
ruItemPrice__c  NUMERIC,
strFinancialReporting_SalesChannel__c VARCHAR(8000),
strOpportunityProductId__c  VARCHAR(8000),
strParentOpportunityProductId__c  VARCHAR(8000),
object_type  VARCHAR(200)  )
;


ALTER TABLE ONLY sfdc.onb2__item__c
    ADD CONSTRAINT onb2__item__c_pkey PRIMARY KEY (Id,LastModifiedDate);




drop table if exists sfdc.onb2__subscription__c ;

create table sfdc.onb2__subscription__c (
CreatedById CHAR(400),
CreatedDate TIMESTAMP,
CurrencyIsoCode VARCHAR(1000),
Id  CHAR(400),
IsDeleted BOOLEAN,
LastActivityDate  DATE,
LastModifiedById  CHAR(400),
LastModifiedDate  TIMESTAMP,
Name  VARCHAR(8000),
ONB2__Account__c  CHAR(400),
ONB2__AggregationPeriod__c  VARCHAR(1000),
ONB2__AutoRenewal__c  VARCHAR(1000),
ONB2__BankAccountOwner__c VARCHAR(8000),
ONB2__BankAccount__c  VARCHAR(8000),
ONB2__BankCode__c VARCHAR(8000),
ONB2__BillingPeriod__c  NUMERIC,
ONB2__CancelationDate__c  DATE,
ONB2__CancelationTerm__c  VARCHAR(1000),
ONB2__Contact__c  CHAR(400),
ONB2__DirectDebitMandateGranted__c  DATE,
ONB2__DirectDebitMandateReference__c  VARCHAR(8000),
ONB2__DirectDebitSequenceType__c  VARCHAR(1000),
ONB2__DiscountPaymentDue__c NUMERIC,
ONB2__DiscountRate__c NUMERIC,
ONB2__DisplayTransactionTables__c BOOLEAN,
ONB2__EmailBCC__c TEXT,
ONB2__EmailInvoiceActive__c BOOLEAN,
ONB2__EmailInvoiceCc__c TEXT,
ONB2__EmailInvoice__c CHAR(400),
ONB2__EndDate__c  DATE,
ONB2__InvoicePaymentMethod__c VARCHAR(1000),
ONB2__LastError__c  TEXT,
ONB2__LastInvoiceRun__c CHAR(400),
ONB2__LegalAccountName__c VARCHAR(8000),
ONB2__LegalCity__c  VARCHAR(8000),
ONB2__LegalCountry__c VARCHAR(8000),
ONB2__LegalPostalCode__c  VARCHAR(8000),
ONB2__LegalState__c VARCHAR(8000),
ONB2__LegalStreet__c  VARCHAR(8000),
ONB2__NextInvoice__c  DATE,
ONB2__PaymentCyclePeriod__c VARCHAR(1000),
ONB2__PaymentCycles__c  NUMERIC,
ONB2__PaymentDue__c NUMERIC,
ONB2__PreferredInvoiceDate__c DATE,
ONB2__PriceIncreaseDate__c  VARCHAR(1000),
ONB2__PriceIncrease__c  NUMERIC,
ONB2__PrintInvoiceContact__c  CHAR(400),
ONB2__PrintInvoice__c BOOLEAN,
ONB2__RenewalDate__c  DATE,
ONB2__ReviewInvoice__c  VARCHAR(1000),
ONB2__StartDate__c  DATE,
ONB2__Status__c VARCHAR(1000),
ONB2__Template__c CHAR(400),
ONB2__Tenant__c VARCHAR(8000),
ON_Type__c  VARCHAR(1000),
OwnerId CHAR(400),
SystemModstamp  TIMESTAMP,
bOpenPaymentCase__c BOOLEAN,
fmlChannel__c VARCHAR(8000),
plChannelCountryCode__c VARCHAR(1000),
plChannelSalesType__c VARCHAR(1000),
plChannelUserRole__c  VARCHAR(1000),
refContract__c  CHAR(400),
object_type  VARCHAR(200) );


ALTER TABLE ONLY sfdc.onb2__subscription__c
    ADD CONSTRAINT onb2__subscription__c_pkey PRIMARY KEY (Id,LastModifiedDate);


drop table if exists sfdc.onb2__dunningdetail__c;

create table sfdc.onb2__dunningdetail__c (
CreatedById CHAR(400),
CreatedDate TIMESTAMP,
CurrencyIsoCode VARCHAR(1000),
Id   CHAR(400),
IsDeleted BOOLEAN,
LastModifiedById   CHAR(400),
LastModifiedDate   TIMESTAMP,
Name   VARCHAR(8000),
ONB2__Amount__c NUMERIC,
ONB2__BalanceDifference__c   NUMERIC,
ONB2__DaysOverdue__c   NUMERIC,
ONB2__Description__c   TEXT,
ONB2__DunningAmount__c   NUMERIC,
ONB2__Dunning__c   CHAR(400),
ONB2__GrandTotal__c NUMERIC,
ONB2__Invoice__c   CHAR(400),
ONB2__LateFee__c   NUMERIC,
ONB2__PaymentDueDate__c DATE,
ONB2__PaymentDue__c NUMERIC,
ONB2__PreviousFees__c NUMERIC,
ONB2__Rate__c NUMERIC,
ONB2__Sequence__c NUMERIC,
ONB2__Title__c   VARCHAR(8000),
ONB2__Type__c VARCHAR(1000),
SystemModstamp   TIMESTAMP,
object_type  VARCHAR(200) );

ALTER TABLE ONLY sfdc.onb2__dunningdetail__c
    ADD CONSTRAINT onb2__dunningdetails__c_pkey PRIMARY KEY (Id,LastModifiedDate);


drop table if exists sfdc.lead ;

create table sfdc.lead (
AnnualRevenue NUMERIC,
BSendInfoMaterial__c   BOOLEAN,
City   VARCHAR(8000),
Company VARCHAR(8000),
ConvertedAccountId   CHAR(400),
ConvertedContactId   CHAR(400),
ConvertedDate DATE,
ConvertedOpportunityId   CHAR(400),
Country VARCHAR(8000),
CreatedById CHAR(400),
CreatedDate TIMESTAMP,
CurrencyIsoCode VARCHAR(1000),
Email CHAR(400),
FirstName VARCHAR(8000),
Id   VARCHAR(400),
Industry   VARCHAR(1000),
IsConverted BOOLEAN,
IsDeleted BOOLEAN,
IsUnreadByOwner BOOLEAN,
LastActivityDate   DATE,
LastModifiedById   CHAR(400),
LastModifiedDate   TIMESTAMP,
LastName   VARCHAR(8000),
LastTransferDate   DATE,
LeadSource   VARCHAR(1000),
MobilePhone VARCHAR(200),
Name   VARCHAR(8000),
NumberOfEmployees NUMERIC,
OwnerId CHAR(400),
Phone VARCHAR(200),
PostalCode   VARCHAR(8000),
Rating   VARCHAR(1000),
RecordTypeId   CHAR(400),
Salutation   VARCHAR(1000),
State VARCHAR(8000),
Status   VARCHAR(1000),
Street   TEXT,
SystemModstamp   TIMESTAMP,
Title VARCHAR(8000),
Website VARCHAR(2000),
bBelongsToChain__c   BOOLEAN,
bDemoSetByOwner__c   BOOLEAN,
bGotReferred__c BOOLEAN,
bOnlineBookingAvailable__c   BOOLEAN,
bRejectLead__c   BOOLEAN,
bSendEmailConfirmation__c BOOLEAN,
bStarLead__c   BOOLEAN,
dNumberOfOutlets__c NUMERIC,
plTemplateLanguage__c VARCHAR(1000),
plType__c VARCHAR(1000),
refAssignedTo__c   CHAR(400),
strCompetitorSystem__c   VARCHAR(8000),
object_type  VARCHAR(200),
urlFacebookProfile__c VARCHAR(2000) );



ALTER TABLE ONLY sfdc.lead
    ADD CONSTRAINT Lead_pkey PRIMARY KEY (Id,LastModifiedDate);


drop table if exists sfdc.users;

create table sfdc.users (
AboutMe TEXT,
AccountId CHAR(400),
Alias VARCHAR(8000),
CallCenterId   CHAR(400),
City   VARCHAR(8000),
CommunityNickname VARCHAR(8000),
CompanyName VARCHAR(8000),
ContactId CHAR(400),
Country VARCHAR(8000),
CreatedById CHAR(400),
CreatedDate TIMESTAMP,
CurrencyIsoCode VARCHAR(1000),
DefaultCurrencyIsoCode   VARCHAR(1000),
DelegatedApproverId CHAR(400),
Department   VARCHAR(8000),
DigestFrequency VARCHAR(1000),
Division   VARCHAR(8000),
Email VARCHAR(400),
EmailEncodingKey   VARCHAR(1000),
EmployeeNumber   VARCHAR(8000),
Extension VARCHAR(200),
Fax VARCHAR(200),
FederationIdentifier   VARCHAR(8000),
FirstName VARCHAR(8000),
ForecastEnabled BOOLEAN,
FullPhotoUrl   VARCHAR(2000),
Id   CHAR(400),
IsActive   BOOLEAN,
IsPortalEnabled BOOLEAN,
LanguageLocaleKey VARCHAR(1000),
LastLoginDate TIMESTAMP,
LastModifiedById   CHAR(400),
LastModifiedDate   TIMESTAMP,
LastName   VARCHAR(8000),
LastPasswordChangeDate   TIMESTAMP,
LocaleSidKey   VARCHAR(1000),
ManagerId CHAR(400),
MobilePhone VARCHAR(200),
Name   VARCHAR(8000),
OfflinePdaTrialExpirationDate TIMESTAMP,
OfflineTrialExpirationDate   TIMESTAMP,
Phone VARCHAR(200),
PortalRole   VARCHAR(1000),
PostalCode   VARCHAR(8000),
ProfileId CHAR(400),
ReceivesAdminInfoEmails BOOLEAN,
ReceivesInfoEmails   BOOLEAN,
SmallPhotoUrl VARCHAR(2000),
State VARCHAR(8000),
Street   TEXT,
SystemModstamp   TIMESTAMP,
Team__c VARCHAR(1000),
TimeZoneSidKey   VARCHAR(1000),
Title VARCHAR(8000),
UserRoleId   CHAR(400),
UserType   VARCHAR(1000),
Username   VARCHAR(8000),
bDisplayProfilePictureCompUserSignature__c   BOOLEAN,
dGMTOffset__c NUMERIC,
plFinancialReporting_SalesChannel__c   VARCHAR(1000),
plGender__c VARCHAR(1000),
strManagerMail__c VARCHAR(400),
strOrganisationNumber__c   TEXT,
object_type  VARCHAR(200),
urlZoomLink__c   VARCHAR(2000)
);

ALTER TABLE ONLY sfdc.users
  ADD CONSTRAINT User_pkey PRIMARY KEY (Id,LastModifiedDate);

    
drop table if exists sfdc.contract;



create table sfdc.contract ( 
AccountId  character(400),
ActivatedById  character(400),
ActivatedDate  timestamp  without  time zone,
BillingCity  character  varying(8000),
BillingCountry     character  varying(8000),
BillingPostalCode  character  varying(8000),
BillingState     character  varying(8000),
BillingStreet  text,
CompanySignedDate  date,
CompanySignedId  character(400),
ContractNumber     character  varying(8000),
ContractTerm      
numeric,
CreatedById  character(400),
CreatedDate  timestamp  without  time zone,
CurrencyIsoCode  character  varying(1000),
CustomerSignedDate     date,
CustomerSignedId     character(400),
CustomerSignedTitle  character  varying(8000),
EndDate  date,
Id     character(400),  
IsDeleted  boolean,
LastActivityDate     date,
LastApprovedDate     timestamp  without  time zone,
LastModifiedById     character(400),
LastModifiedDate     timestamp  without  time zone,
Name     character  varying(8000),
OwnerId  character(400),
Pricebook2Id     character(400),
RecordTypeId     character(400),
ShippingCity     character  varying(8000),
ShippingCountry  character  varying(8000),
ShippingPostalCode     character  varying(8000),
ShippingState  character  varying(8000),
ShippingStreet     text,
SpecialTerms     text,
StartDate  date,
Status     character  varying(1000),
StatusCode     character  varying(1000),
SystemModstamp     timestamp  without  time zone,
bBonusOnHold__c  boolean,
bEdgeCase__c     boolean,
dAverageSalesMRR__c  numeric,
dGuaranteedBookings__c     numeric,
dYearlyDiscount__c     numeric,
dateCancellationPeriod__c  date,
plEdgeCaseCategory__c  character  varying(1000),  
plMoneyBack__c     character  varying(1000),
plPaymentCycle__c  character  varying(1000),
plSpecialRightOfCancellation__c  character  varying(1000),
plTrial__c     character  varying(1000),
refAccountmanagerCash__c     character(400),
refAccountmanager__c     character(400),
refBusinessOwner__c  character(400),
refContactPerson__c  character(400),
refOpportunity__c  character(400),
refSubscription__c     character(400),
strFinancialReporting_SalesChannel__c  character  varying(8000),
strPaymentMethod__c  character  varying(1000),
object_type     VARCHAR(200)
);

ALTER TABLE ONLY sfdc.contract
    ADD CONSTRAINT contract_pkey PRIMARY KEY (Id,LastModifiedDate);




drop table if exists sfdc.recordtype;

create table sfdc.recordtype (

BusinessProcessId CHAR(400),
CreatedById CHAR(400),
CreatedDate TIMESTAMP,
Description VARCHAR(8000),
DeveloperName VARCHAR(8000),
Id  CHAR(400),
IsActive  BOOLEAN,
LastModifiedById  CHAR(400),
LastModifiedDate  TIMESTAMP,
Name  VARCHAR(8000),
NamespacePrefix VARCHAR(8000),
SobjectType VARCHAR(8000),
SystemModstamp  TIMESTAMP,
object_type VARCHAR(200)
);

ALTER TABLE ONLY sfdc.recordtype
    ADD CONSTRAINT recordtype_pkey PRIMARY KEY (Id,LastModifiedDate);




drop table if exists sfdc.onb2__balance__c;

create table sfdc.onb2__balance__c (

CreatedById CHAR(400),
CreatedDate TIMESTAMP,
CurrencyIsoCode VARCHAR(1000),
Id  CHAR(400),
IsDeleted BOOLEAN,
LastActivityDate  DATE,
LastModifiedById  CHAR(400),
LastModifiedDate  TIMESTAMP,
Name  VARCHAR(8000),
ONB2__Account__c  CHAR(400),
ONB2__Amount__c NUMERIC,
ONB2__Date__c DATE,
ONB2__Dunning__c  CHAR(400),
ONB2__Invoice__c  CHAR(400),
ONB2__NoAutoAssignment__c BOOLEAN,
ONB2__PaymentMethod__c  VARCHAR(1000),
ONB2__PaymentProvider__c  VARCHAR(1000),
ONB2__Reference__c  VARCHAR(8000),
ONB2__RelatedInvoice__c CHAR(400),
ONB2__Subscription__c CHAR(400),
ONB2__TransactionNo__c  VARCHAR(8000),
ONB2__Type__c VARCHAR(1000),
SystemModstamp  TIMESTAMP,
object_type  VARCHAR(200)
);


ALTER TABLE ONLY sfdc.onb2__balance__c
    ADD CONSTRAINT onb2__balance__c_pkey PRIMARY KEY (Id,LastModifiedDate);




drop table if exists sfdc.account;

create table sfdc.account(

BillingCity  VARCHAR(8000),
BillingCountry   VARCHAR(8000),
BillingPostalCode  VARCHAR(8000),
BillingState   VARCHAR(8000),
BillingStreet  VARCHAR(8000),
CreatedById  CHAR(400),
CreatedDate  TIMESTAMP,
CurrencyIsoCode  VARCHAR(8000),
Id   CHAR(400),
Industry   VARCHAR(8000),
IsDeleted  BOOLEAN,
LastActivityDate   DATE,
LastModifiedById   CHAR(400),
LastModifiedDate   TIMESTAMP,
Merchant_Happiness__c  VARCHAR(8000),
Name   VARCHAR(8000),
NumberOfEmployees  NUMERIC,
OwnerId  CHAR(400),
ParentId   CHAR(400),
Phone  VARCHAR(8000),
Rating   VARCHAR(8000),
RecordTypeId   CHAR(400),
Type   VARCHAR(8000),
Website  VARCHAR(8000),
bAccountRisk__c  BOOLEAN,
bActive__c   BOOLEAN,
bIsPartner__c  BOOLEAN,
dCRMScore__c   NUMERIC,
dCustomerScore__c  NUMERIC,
dInventoryScore__c   NUMERIC,
dKeyAccountId__c   NUMERIC,
dShopId__c   NUMERIC,
dTotalActivityScore__c   NUMERIC,
dTractionScore__c  NUMERIC,
dateDateCustomerImport__c  DATE,
dateDebtCollectionInitiated__c   DATE,
dateInternalUse__c   DATE,
dateScall__c   DATE,
dateTrialEnd__c  DATE,
dateTrialStart__c  DATE,
dateWidgetIn__c  DATE,
dtActivationDate__c  DATE,
dtCRNumberOfCustomersImported__c   NUMERIC,
dtOnboardingDate__c  DATE,
fmlSubscriptionStatus__c VARCHAR(4000),
plCreditworthiness__c  VARCHAR(8000),
plCustomerDataInfo__c  VARCHAR(8000),
plSubcategory__c   VARCHAR(8000),
refActiveSubscription__c   CHAR(400),
strCreditScore__c  VARCHAR(8000),
strMerchantUUID__c   VARCHAR(8000),
object_type   VARCHAR(8000),
urlLinkToSuccessStory__c   VARCHAR(8000)

);

ALTER TABLE ONLY sfdc.account
    ADD CONSTRAINT Account_pkey PRIMARY KEY (Id,LastModifiedDate);



drop table if exists sfdc.opportunity;

create table sfdc.opportunity (
AccountId  CHAR(400),
Amount  NUMERIC,
CloseDate  DATE,
CreatedById  VARCHAR(400),
CreatedDate  TIMESTAMP,
CurrencyIsoCode  VARCHAR(400),
HasOpportunityLineItem  BOOLEAN,
Id  CHAR(400),
IsClosed  BOOLEAN,
IsDeleted  BOOLEAN,
IsWon  BOOLEAN,
LastActivityDate  DATE,
LastModifiedById  VARCHAR(400),
LastModifiedDate  TIMESTAMP,
LeadSource  VARCHAR(400),
Name  VARCHAR(8000),
NextStep  VARCHAR(8000),
OwnerId  VARCHAR(400),
Pricebook2Id  VARCHAR(400),
Probability  NUMERIC,
RecordTypeId  VARCHAR(400),
StageName  VARCHAR(400),
SystemModstamp  TIMESTAMP,
TotalOpportunityQuantity  NUMERIC,
Type  VARCHAR(400),
bDemoSetByOwner__c  BOOLEAN,
bOnlineBookingAvailable__c  BOOLEAN,
bTrialClosed__c  BOOLEAN,
curIncrementalMRR__c  NUMERIC,
dateTrialCloseDate__c  DATE,
dateTrialEndDate__c  DATE,
dateTrialStartDate__c  DATE,
fmlChannelCountryCode__c  VARCHAR(8000),
fmlChannelSalesType__c  VARCHAR(8000),
fmlChannelUserRole__c  VARCHAR(8000),
fmlChannel__c  VARCHAR(8000),
strCompetitorSystem__c  VARCHAR(8000),
object_type  VARCHAR(400)
);

ALTER TABLE ONLY sfdc.opportunity
    ADD CONSTRAINT opportunity_pkey PRIMARY KEY (Id,LastModifiedDate);


drop table if exists sfdc.contact;

create table sfdc.contact (

AccountId CHAR(400),
Birthdate DATE,
CreatedById CHAR(400),
CreatedDate TIMESTAMP,
CurrencyIsoCode VARCHAR(200),
Department  VARCHAR(200),
Email VARCHAR(200),
FirstName VARCHAR(200),
HomePhone VARCHAR(200),
Id  VARCHAR(400),
IsDeleted BOOLEAN,
LastActivityDate  DATE,
LastModifiedById  CHAR(400),
LastModifiedDate  TIMESTAMP,
LastName  VARCHAR(200),
LeadSource  VARCHAR(200),
MailingCity VARCHAR(200),
MailingCountry  VARCHAR(200),
MailingPostalCode VARCHAR(200),
MailingState  VARCHAR(200),
MailingStreet VARCHAR(2000),
MobilePhone VARCHAR(200),
Name  VARCHAR(200),
OwnerId CHAR(400),
Phone VARCHAR(200),
RecordTypeId  CHAR(400),
ReportsToId CHAR(400),
Salutation  VARCHAR(200),
SystemModstamp  TIMESTAMP,
Title VARCHAR(200),
object_type VARCHAR(200)
);

ALTER TABLE ONLY sfdc.contact
    ADD CONSTRAINT contact_pkey PRIMARY KEY (Id,LastModifiedDate);




drop table if exists sfdc.onb2__dunning__c;

create table sfdc.onb2__dunning__c (
CreatedById CHAR(400),
CreatedDate TIMESTAMP,
CurrencyIsoCode VARCHAR(400),
ESRExportDate__c DATE,
Id VARCHAR(400),
IsDeleted BOOLEAN,
LastActivityDate DATE,
LastModifiedById CHAR(400),
LastModifiedDate TIMESTAMP,
Name VARCHAR(1000),
ONB2__AccountName__c VARCHAR(1000),
ONB2__Account__c CHAR(400),
ONB2__BillingAddress__c VARCHAR(2000),
ONB2__BillingCity__c VARCHAR(1000),
ONB2__BillingCountry__c VARCHAR(1000),
ONB2__BillingPostalCode__c VARCHAR(1000),
ONB2__BillingState__c VARCHAR(1000),
ONB2__BillingStreet__c VARCHAR(1000),
ONB2__Contact__c CHAR(400),
ONB2__Date__c DATE,
ONB2__DisplayType__c VARCHAR(1000),
ONB2__DunningRun__c CHAR(400),
ONB2__EmailBCC__c VARCHAR(2000),
ONB2__EmailCC__c VARCHAR(2000),
ONB2__EmailContact__c CHAR(400),
ONB2__EmailDunning__c BOOLEAN,
ONB2__EmailError__c VARCHAR(1000),
ONB2__EmailFirstName__c VARCHAR(1000),
ONB2__EmailLastName__c VARCHAR(1000),
ONB2__EmailSalutation__c VARCHAR(1000),
ONB2__EmailStatus__c VARCHAR(400),
ONB2__Email__c VARCHAR(200),
ONB2__FlatFee__c NUMERIC,
ONB2__Footer__c VARCHAR(2000),
ONB2__GrandTotal__c NUMERIC,
ONB2__Header__c VARCHAR(2000),
ONB2__InfoLeft__c VARCHAR(2000),
ONB2__InfoRight__c VARCHAR(2000),
ONB2__LateFee__c NUMERIC,
ONB2__Level__c NUMERIC,
ONB2__MailingCity__c VARCHAR(1000),
ONB2__MailingContact__c CHAR(400),
ONB2__MailingCountry__c VARCHAR(1000),
ONB2__MailingFirstName__c VARCHAR(1000),
ONB2__MailingLastName__c VARCHAR(1000),
ONB2__MailingPostalCode__c VARCHAR(1000),
ONB2__MailingSalutation__c VARCHAR(1000),
ONB2__MailingState__c VARCHAR(1000),
ONB2__MailingStreet__c VARCHAR(1000),
ONB2__MaxSequence__c NUMERIC,
ONB2__PDF__c VARCHAR(1000),
ONB2__PageHeader__c VARCHAR(2000),
ONB2__PaymentDueDate__c DATE,
ONB2__PaymentDue__c NUMERIC,
ONB2__PrintDunning__c BOOLEAN,
ONB2__RecipientAddress__c VARCHAR(2000),
ONB2__SenderAddress__c VARCHAR(1000),
ONB2__Status__c VARCHAR(400),
ONB2__Template__c CHAR(400),
ONB2__Tenant__c VARCHAR(1000),
ONB2__Text1__c VARCHAR(2000),
ONB2__Text2__c VARCHAR(2000),
ONB2__Text3__c VARCHAR(2000),
ONB2__Type__c VARCHAR(1000),
ONB2__UUID__c VARCHAR(1000),
OwnerId CHAR(400),
SystemModstamp TIMESTAMP,
strESRParticipantNumber__c VARCHAR(1000),
strESRReferenceNumber__c VARCHAR(1000),
object_type  VARCHAR(200)
);

ALTER TABLE ONLY sfdc.onb2__dunning__c
    ADD CONSTRAINT onb2__dunning__c_pkey PRIMARY KEY (Id,LastModifiedDate);


